/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.internal;

import codigo.proforma.codProf_Busquedas;
import codigo.busqueda.codBus_Busqueda;
import java.util.Iterator;

/**
 *
 * @author Mipc
 */
public class itf_Busqueda extends javax.swing.JInternalFrame {

    codProf_Busquedas codBusqueda = new codProf_Busquedas();
    codBus_Busqueda cBusqueda = new codBus_Busqueda();

    public itf_Busqueda() {
        initComponents();
        try {
            codBusqueda.llenarComboCategoria(cboCategoria);

            cBusqueda.setNroProforma(txtProforma.getText());
            cBusqueda.setCodigo(txtCodigo.getText());
            cBusqueda.setProducto(txtProducto.getText());
            cBusqueda.setCategoria(cboCategoria.getSelectedItem().toString());
            cBusqueda.mostrarTablaBusqueda(tablaItems);
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaItems = new javax.swing.JTable();
        txtProforma = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        chekProforma = new javax.swing.JCheckBox();
        chekCodigo = new javax.swing.JCheckBox();
        chekProducto = new javax.swing.JCheckBox();
        chekCategoria = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTotalPaquete = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalUnidades = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalGeneral = new javax.swing.JTextField();
        txtTotalImporte = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Proforma", "Fecha", "Formato", "Tipo", "U. Medida", "Cantidad", "Categoria", "Descripcion", "P. Unitario", "Importe"
            }
        ));
        jScrollPane1.setViewportView(tablaItems);

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        chekProforma.setSelected(true);
        chekProforma.setText("NroProforma");
        chekProforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekProformaActionPerformed(evt);
            }
        });

        chekCodigo.setSelected(true);
        chekCodigo.setText("Mini Codigo");
        chekCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekCodigoActionPerformed(evt);
            }
        });

        chekProducto.setSelected(true);
        chekProducto.setText("Producto");
        chekProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekProductoActionPerformed(evt);
            }
        });

        chekCategoria.setSelected(true);
        chekCategoria.setText("Categoria");
        chekCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekCategoriaActionPerformed(evt);
            }
        });

        jLabel9.setText("TOTAL Paquete");

        jLabel10.setText("TOTAL Unidades");

        jLabel11.setText("TOTAL General");

        jLabel8.setText("TOTAL Importe");

        jLabel1.setText("s\\.");

        jLabel2.setText("s\\.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTotalUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProforma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chekProforma))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chekCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chekProducto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chekCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chekProforma)
                            .addComponent(chekCodigo)
                            .addComponent(chekProducto)
                            .addComponent(chekCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String nroproforma="",codigo="",producto="",categoria="";
        if (chekProforma.isSelected()) {
            nroproforma=txtProforma.getText();
        }
        if (chekCodigo.isSelected()) {
            codigo=txtCodigo.getText();
        }
        if (chekProducto.isSelected()) {
            producto=txtProducto.getText();
        }
        if (chekCategoria.isSelected()) {
            categoria=cboCategoria.getSelectedItem().toString();
        }
        
        cBusqueda.setNroProforma(nroproforma);
        cBusqueda.setCodigo(codigo);
        cBusqueda.setProducto(producto);
        cBusqueda.setCategoria(categoria);
        cBusqueda.mostrarTablaBusqueda(tablaItems);
        
        int contarPaquete=0;
        int contarUnidad=0;
        double contarImporte=0;
        
        for (int i = 0; i < tablaItems.getRowCount(); i++) {
            if (tablaItems.getValueAt(i, 4).equals("Paquete")) {
                //contarPaquete=contarPaquete+1;
                contarPaquete=contarPaquete+Integer.parseInt(tablaItems.getValueAt(i, 6).toString());
            }else{
                //    contarUnidad=contarUnidad+1;
                contarUnidad=contarUnidad+Integer.parseInt(tablaItems.getValueAt(i, 6).toString());
            }
            
               contarImporte=contarImporte+ Double.parseDouble(tablaItems.getValueAt(i, 10).toString());
        }
        txtTotalPaquete.setText(""+contarPaquete);
        txtTotalUnidades.setText(""+contarUnidad);
         txtTotalImporte.setText(""+contarImporte);
        
//        codProforma.setNumProforma(txtProforma.getText());
//        codProforma.setProducto(txtProducto.getText());
//        codProforma.setCategoria(cboCategoria.getSelectedItem().toString());
//        codProforma.llenarTablaItems(tablaItems);
//
//        txtTotal.setText("" + codProforma.sumarFilas(tablaItems));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void chekProformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekProformaActionPerformed
        txtProforma.setText("");
        if (chekProforma.isSelected()) {
            txtProforma.setEnabled(true);
        } else {
            txtProforma.setEnabled(false);
        }

    }//GEN-LAST:event_chekProformaActionPerformed

    private void chekCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekCodigoActionPerformed
        txtCodigo.setText("");
        if (chekCodigo.isSelected()) {
            txtCodigo.setEnabled(true);
        } else {
            txtCodigo.setEnabled(false);
        }
    }//GEN-LAST:event_chekCodigoActionPerformed

    private void chekProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekProductoActionPerformed
        txtProducto.setText("");
        if (chekProducto.isSelected()) {
            txtProducto.setEnabled(true);
        } else {
            txtProducto.setEnabled(false);
        }
    }//GEN-LAST:event_chekProductoActionPerformed

    private void chekCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekCategoriaActionPerformed

        if (chekCategoria.isSelected()) {
            cboCategoria.setEnabled(true);
        } else {
            cboCategoria.setEnabled(false);
        }
    }//GEN-LAST:event_chekCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCategoria;
    private javax.swing.JCheckBox chekCategoria;
    private javax.swing.JCheckBox chekCodigo;
    private javax.swing.JCheckBox chekProducto;
    private javax.swing.JCheckBox chekProforma;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaItems;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProforma;
    private javax.swing.JTextField txtTotalGeneral;
    private javax.swing.JTextField txtTotalImporte;
    private javax.swing.JTextField txtTotalPaquete;
    private javax.swing.JTextField txtTotalUnidades;
    // End of variables declaration//GEN-END:variables
}
